definitions:
  api.GetTestResponse:
    properties:
      config:
        additionalProperties: {}
        type: object
      configVars:
        additionalProperties:
          type: string
        type: object
      id:
        type: string
      name:
        type: string
      schedule:
        $ref: '#/definitions/types.TestSchedule'
      source:
        type: string
      timeout:
        type: integer
    type: object
  api.GetTestRunDetailedTask:
    properties:
      completed:
        type: boolean
      config_yaml:
        type: string
      index:
        type: integer
      log:
        items:
          $ref: '#/definitions/api.GetTestRunDetailedTaskLog'
        type: array
      name:
        type: string
      parent_index:
        type: integer
      result:
        type: string
      result_error:
        type: string
      runtime:
        type: integer
      start_time:
        type: integer
      started:
        type: boolean
      status:
        type: string
      stop_time:
        type: integer
      timeout:
        type: integer
      title:
        type: string
    type: object
  api.GetTestRunDetailedTaskLog:
    properties:
      data:
        additionalProperties:
          type: string
        type: object
      datalen:
        type: integer
      level:
        type: integer
      msg:
        type: string
      time:
        type: string
    type: object
  api.GetTestRunDetailsResponse:
    properties:
      name:
        type: string
      run_id:
        type: integer
      start_time:
        type: integer
      status:
        $ref: '#/definitions/types.TestStatus'
      stop_time:
        type: integer
      tasks:
        items:
          $ref: '#/definitions/api.GetTestRunDetailedTask'
        type: array
      test_id:
        type: string
    type: object
  api.GetTestRunResponse:
    properties:
      name:
        type: string
      run_id:
        type: integer
      start_time:
        type: integer
      status:
        $ref: '#/definitions/types.TestStatus'
      stop_time:
        type: integer
      tasks:
        items:
          $ref: '#/definitions/api.GetTestRunTask'
        type: array
      test_id:
        type: string
    type: object
  api.GetTestRunTask:
    properties:
      completed:
        type: boolean
      index:
        type: integer
      name:
        type: string
      parent_index:
        type: integer
      result:
        type: string
      result_error:
        type: string
      runtime:
        type: integer
      start_time:
        type: integer
      started:
        type: boolean
      status:
        type: string
      stop_time:
        type: integer
      timeout:
        type: integer
      title:
        type: string
    type: object
  api.GetTestRunsResponse:
    properties:
      name:
        type: string
      run_id:
        type: integer
      start_time:
        type: integer
      status:
        $ref: '#/definitions/types.TestStatus'
      stop_time:
        type: integer
      test_id:
        type: string
    type: object
  api.GetTestsResponse:
    properties:
      id:
        type: string
      name:
        type: string
      source:
        type: string
    type: object
  api.PostTestRunRequest:
    properties:
      config:
        additionalProperties: {}
        type: object
    type: object
  api.PostTestRunResponse:
    properties:
      config:
        additionalProperties: {}
        type: object
      name:
        type: string
      run_id:
        type: integer
      test_id:
        type: string
    type: object
  github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response:
    properties:
      data: {}
      status:
        type: string
    type: object
  types.TestSchedule:
    properties:
      cron:
        items:
          type: string
        type: array
      file:
        type: boolean
    type: object
  types.TestStatus:
    enum:
    - pending
    - running
    - success
    - failure
    - skipped
    type: string
    x-enum-varnames:
    - TestStatusPending
    - TestStatusRunning
    - TestStatusSuccess
    - TestStatusFailure
    - TestStatusSkipped
info:
  contact: {}
  description: API for querying information about Assertoor tests
  title: Assertoor API Documentation
  version: "1.0"
paths:
  /api/v1/test/{testId}:
    get:
      description: Returns the test definition with given ID.
      operationId: getTest
      parameters:
      - description: ID of the test definition to get details for
        in: path
        name: testId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
            - properties:
                data:
                  $ref: '#/definitions/api.GetTestResponse'
              type: object
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
      summary: Get test definition by test ID
      tags:
      - Test
  /api/v1/test/{testId}/run:
    post:
      description: Returns the test & run id of the scheduled test execution.
      operationId: postTestRun
      parameters:
      - description: ID of the test definition to schedule a test run for
        in: path
        name: testId
        required: true
        type: string
      - description: Rest run options
        in: body
        name: runOptions
        required: true
        schema:
          $ref: '#/definitions/api.PostTestRunRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
            - properties:
                data:
                  $ref: '#/definitions/api.PostTestRunResponse'
              type: object
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
      summary: Schedule new test run by test ID
      tags:
      - Test
  /api/v1/test_run/{runId}:
    get:
      description: Returns the run details with given ID. Includes a summary and a
        list of task with limited details
      operationId: getTestRun
      parameters:
      - description: ID of the test run to get details for
        in: path
        name: runId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
            - properties:
                data:
                  $ref: '#/definitions/api.GetTestRunResponse'
              type: object
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
      summary: Get test run by run ID
      tags:
      - TestRun
  /api/v1/test_run/{runId}/details:
    get:
      description: Returns the run details with given ID. Includes a summary and a
        list of task with all details (incl. logs & task configurations)
      operationId: getTestRunDetails
      parameters:
      - description: ID of the test run to get details for
        in: path
        name: runId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
            - properties:
                data:
                  $ref: '#/definitions/api.GetTestRunDetailsResponse'
              type: object
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
      summary: Get detailed test run by run ID
      tags:
      - TestRun
  /api/v1/test_run/{runId}/status:
    get:
      description: Returns the run status with given ID.
      operationId: getTestRunStatus
      parameters:
      - description: ID of the test run to get the status for
        in: path
        name: runId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
      summary: Get test run status by run ID
      tags:
      - TestRun
  /api/v1/test_runs:
    get:
      description: Returns a list of all test runs.
      operationId: getTestRuns
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/api.GetTestRunsResponse'
                  type: array
              type: object
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
      summary: Get list of test runs
      tags:
      - TestRun
  /api/v1/tests:
    get:
      description: Returns the list of test definitions. These test definitions can
        be used to create new test runs and are supplied via the assertoor configuration.
      operationId: getTests
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/api.GetTestsResponse'
                  type: array
              type: object
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/github_com_ethpandaops_assertoor_pkg_coordinator_web_api.Response'
      summary: Get list of test definitions
      tags:
      - Test
swagger: "2.0"
tags:
- description: All endpoints related to test definitions
  name: Test
- description: All endpoints related to test runs
  name: TestRun
