id: generate-attestations
name: "Generate Attestations"
timeout: 1h
config:
  validatorMnemonic: "giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete"
  validatorStartIndex: 0
  validatorCount: 100
  attestationEpochs: 3
  lastEpochAttestations: false
  sendAllLastEpoch: false
  lateHead: 0
  randomLateHead: ""
  lateHeadClusterSize: 1
tasks:
- name: check_clients_are_healthy
  title: "Check if at least one client is ready"
  timeout: 5m
  config:
    minClientCount: 1

- name: run_tasks
  title: "Run tasks"
  config:
    stopChildOnResult: false
    tasks:
    - name: generate_attestations
      title: "Generate attestations for 3 epochs"
      configVars:
        mnemonic: "validatorMnemonic"
        startIndex: "validatorStartIndex"
        indexCount: "validatorCount"
        limitEpochs: "attestationEpochs"
        lastEpochAttestations: "lastEpochAttestations"
        sendAllLastEpoch: "sendAllLastEpoch"
        lateHead: "lateHead"
        randomLateHead: "randomLateHead"
        lateHeadClusterSize: "lateHeadClusterSize"
