id: tx-pool-check
name: "Check transaction pool"
timeout: 2h
disable: false
config:
  walletPrivkey: ""
tasks:
- name: tx_pool_latency_analysis
  title: "Check transaction pool latency with 1.000 transactions"
  timeout: 5m
  config:
    tps: 1000
    durationS: 10
    logInterval: 1000
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  timeout: 5m
  config:
    waitTime: 5
- name: tx_pool_throughput_analysis
  timeout: 5m
  title: "Check transaction pool throughput with 1.000 transactions in one second"
  config:
    tps: 1000
    durationS: 10
    logInterval: 1000
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  timeout: 5m
  config:
    waitTime: 5
- name: tx_pool_latency_analysis
  title: "Check transaction pool latency with 5.000 transactions"
  timeout: 5m
  config:
    tps: 5000
    durationS: 5
    logInterval: 2000
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  timeout: 15m
  config:
    waitTime: 5
- name: tx_pool_throughput_analysis
  timeout: 5m
  title: "Check transaction pool throughput with 5.000 transactions in one second"
  config:
    tps: 5000
    durationS: 5
    logInterval: 2000
  configVars:
    privateKey: "walletPrivkey"
