id: tx-pool-check
name: "Check transaction pool"
timeout: 2h
disable: false
config:
  walletPrivkey: ""
  # validatorPairNames: []
  # minBlobCount: 3
tasks:
- name: tx_pool_throughput_analysis
  title: "Check transaction pool throughput with 1.000 transactions in one second"
  config:
    nonce: 0
    txCount: 1000
    measureInterval: 100
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  config:
    waitTime: 5
- name: tx_pool_latency_analysis
  title: "Check transaction pool latency with 1.000 transactions"
  config:
    nonce: 1000
    txCount: 1000
    measureInterval: 100
    expectedLatency: 500
    failOnHighLatency: true
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  config:
    waitTime: 5
- name: tx_pool_throughput_analysis
  title: "Check transaction pool throughput with 10.000 transactions in one second"
  config:
    nonce: 2000
    txCount: 10000
    measureInterval: 1000
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  config:
    waitTime: 5
- name: tx_pool_latency_analysis
  title: "Check transaction pool latency with 10.000 transactions"
  config:
    nonce: 12000
    txCount: 10000
    measureInterval: 1000
    expectedLatency: 500
    failOnHighLatency: true
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  config:
    waitTime: 5
- name: tx_pool_throughput_analysis
  title: "Check transaction pool throughput with 15.000 transactions in one second"
  config:
    nonce: 22000
    txCount: 15000
    measureInterval: 1500
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  config:
    waitTime: 5
- name: tx_pool_latency_analysis
  title: "Check transaction pool latency with 15.000 transactions"
  config:
    nonce: 37000
    txCount: 15000
    measureInterval: 1500
    expectedLatency: 500
    failOnHighLatency: true
  configVars:
    privateKey: "walletPrivkey"
