id: tx-pool-check
name: "Check transaction pool"
timeout: 1h
disable: false
config:
  walletPrivkey: ""
tasks:
- name: tx_pool_throughput_analysis
  title: "Check transaction pool throughput with 1.000 transactions in one second"
  config:
    qps: 1000
    measureInterval: 100
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  config:
    waitTime: 5
- name: tx_pool_latency_analysis
  title: "Check transaction pool latency with 1.000 transactions"
  config:
    txCount: 1000
    measureInterval: 100
    highLatency: 5000
    failOnHighLatency: true
    secondsBeforeRunning: 15
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  config:
    waitTime: 5
- name: tx_pool_throughput_analysis
  title: "Check transaction pool throughput with 10.000 transactions in one second"
  config:
    qps: 10000
    measureInterval: 1000
    secondsBeforeRunning: 15
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  config:
    waitTime: 5
- name: tx_pool_latency_analysis
  title: "Check transaction pool latency with 10.000 transactions"
  config:
    txCount: 10000
    measureInterval: 1000
    highLatency: 5000
    failOnHighLatency: true
    secondsBeforeRunning: 15
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  config:
    waitTime: 5
- name: tx_pool_throughput_analysis
  title: "Check transaction pool throughput with 15.000 transactions in one second"
  config:
    qps: 15000
    measureInterval: 1500
    secondsBeforeRunning: 15
  configVars:
    privateKey: "walletPrivkey"
- name: tx_pool_clean
  title: "Clean transaction pool"
  config:
    waitTime: 5
- name: tx_pool_latency_analysis
  title: "Check transaction pool latency with 15.000 transactions"
  config:
    txCount: 15000
    measureInterval: 1500
    highLatency: 5000
    failOnHighLatency: true
    secondsBeforeRunning: 15
  configVars:
    privateKey: "walletPrivkey"
